# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='deadline',
            field=models.DateField(),
        ),
    ]
